{% set name = "nsls2-analysis" %}
{% set year = "2020" %}
{% set cycle = "2" %}
{% set version = "0" %}

package:
  name: {{ name|lower }}
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 4
  skip: true  # [py<37 or not linux]

requirements:
  host:
    - python
  run:
    - python
    - analysis ==2020C2.0=*_7
    - chxtools
    - csxtools
    - edrixs
    - eiger-io
    - hxntools
    - ispyb
    - isstools
    - nslsii  # needed for transforms at CSX
    - py4xs
    - sixtools
    # - xpdan

test:
  requires:
    - nsls2forge-utils
  imports:
    - area_detector_handlers
    - bluesky
    - dask
    - databroker
    - event_model
    - lmfit
    - matplotlib
    - numpy
    - ophyd
    - oscars
    - peakutils
    - pymongo
    - pyxrf
    - skbeam
    - suitcase.csv
    - suitcase.json_metadata
    - suitcase.jsonl
    - suitcase.mongo_embedded
    - suitcase.mongo_normalized
    - suitcase.msgpack
    - suitcase.specfile
    - suitcase.tiff_series
    - suitcase.tiff_stack
    - suitcase.utils
    - xray_vision
    # Beamline-specific packages
    - chxtools
    - csxtools
    - edrixs
    - eiger_io
    - hxntools
    - ispyb
    - isstools
    - nslsii
    - py4xs
    - sixtools
  commands:
    # Fail if the "conda-forge" channel is in the list of channels.
    - check-results -t channels -f conda-forge
    # Fail if versions of the packages are not as expected minimum ones.
    - check-results -t version -p bluesky     -e 1.6
    - check-results -t version -p databroker  -e 1.0
    - check-results -t version -p event_model -e 1.15
    - check-results -t version -p ophyd       -e 1.4
    - python -V
    - ipython -V
    - nexpy --help
    - conda-pack --help

about:
  home: https://github.com/NSLS-II
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Bluesky analysis metapackage for NSLS-II beamlines
