{% set name = "nsls2-analysis" %}
{% set year = "2020" %}
{% set cycle = "2" %}
{% set version = "0" %}

package:
  name: {{ name|lower }}
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0
  skip: true  # [py<37 or not linux]

requirements:
  host:
    - python
  run:
    - python
    - analysis ==2020C2.0
    - chxtools
    - csxtools
    - edrixs
    - eiger-io
    - hxntools
    - isstools
    - py4xs
    - sixtools
    # - xpdan

test:
  requires:
    - nsls2forge-utils
  imports:
    - bluesky
    - dask
    - databroker
    - event_model
    - lmfit
    - matplotlib
    - numpy
    - ophyd
    - oscars
    - peakutils
    - pymongo
    - skbeam
    - suitcase.csv
    - suitcase.json_metadata
    - suitcase.jsonl
    - suitcase.mongo_embedded
    - suitcase.mongo_normalized
    - suitcase.msgpack
    - suitcase.specfile
    - suitcase.tiff_series
    - suitcase.tiff_stack
    - suitcase.utils
    - xray_vision
    - chxtools
    - csxtools
    - edrixs
    - eiger_io
    - hxntools
    - isstools
    - py4xs
    - sixtools
  commands:
    # Fail if the "conda-forge" channel is in the list of channels.
    
    # The conda-forge channel does not appear when building locally using a
    # different Docker image.
    # (host) $ docker run -it --rm -v $PWD:/build nsls2/debian-with-miniconda:v0.1.2 bash
    # $ conda create -n test -c nsls2forge -c defaults --override-channels analysis=2020C2.0 chxtools csxtools edrixs eiger-io hxntools isstools py4xs sixtools
    
    # TODO: make it working again in the cloud.
    # - check-results -t channels -f conda-forge

    # Fail if versions of the packages are not as expected minimum ones.
    - check-results -t version -p bluesky     -e 1.6
    - check-results -t version -p event_model -e 1.15
    - check-results -t version -p ophyd       -e 1.4
    - check-results -t version -p databroker  -e 1.0
    - python -V
    - ipython -V
    - nexpy --help

about:
  home: https://github.com/NSLS-II
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Bluesky analysis metapackage for NSLS-II beamlines
