{% set name = "nsls2-analysis" %}
{% set year = "2021" %}
{% set cycle = "1" %}
{% set version = "2" %}

package:
  name: {{ name|lower }}
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 1
  skip: true  # [py<37 or not linux]

requirements:
  host:
    - python
  run:
    - python
    - analysis ==2021C1.2=*_2
    - chxtools
    - csxtools
    - edrixs
    - eiger-io
    - hxntools >=0.5
    - igor
    - ispyb
    - isstools
    - legacy-suitcase
    - lixtools
    - nsls2-detector-handlers >=0.0.2
    - nslsii >=0.1.1  # needed for transforms at csx
    - pdfstream
    - py4xs
    - pyqtgraph
    - sixtools
    - xpdan

test:
  requires:
    - nsls2forge-utils
  imports:
    - area_detector_handlers
    - bluesky
    - dask
    - databroker
    - event_model
    - lmfit
    - matplotlib
    - napari
    - numpy
    - ophyd
    - oscars
    - peakutils
    - pymongo
    - pyxrf
    - skbeam
    - suitcase.csv
    - suitcase.json_metadata
    - suitcase.jsonl
    - suitcase.mongo_embedded
    - suitcase.mongo_normalized
    - suitcase.msgpack
    - suitcase.specfile
    - suitcase.tiff_series
    - suitcase.tiff_stack
    - suitcase.utils
    - xray_vision
    # Beamline-specific packages
    - chxtools
    - csxtools
    - edrixs
    - eiger_io
    - hxntools
    - ispyb
    - isstools
    - lixtools
    - nslsii
    - py4xs
    - sixtools
  files:
    - test.xlsx
  commands:
    # Fail if the "conda-forge" channel is in the list of channels.
    - check-results -t channels -f conda-forge
    # Fail if versions of the packages are not as expected minimum ones.
    - check-results -t version -p bluesky     -e 1.6
    - check-results -t version -p databroker  -e 1.2
    - check-results -t version -p event_model -e 1.17
    - check-results -t version -p nslsii      -e 0.1.1
    - check-results -t version -p ophyd       -e 1.6
    - python -V
    - ipython -V
    - conda-pack --help
    - napari --help
    - napari --version
    - nexpy --help
    - python -c "import pandas; print(pandas.read_excel('test.xlsx'))"

about:
  home: https://github.com/NSLS-II
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Bluesky analysis metapackage for NSLS-II beamlines
