{% set name = "nsls2-analysis" %}
{% set year = "2020" %}
{% set cycle = "2" %}
{% set version = "0" %}

package:
  name: {{ name|lower }}
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0
  skip: True  # [py<36]

requirements:
  host:
    - python
  run:
    - python
    - analysis ==2020C2.0
    - chxtools
    - csxtools
    - edrixs
    - eiger-io
    - hxntools
    - isstools
    - py4xs
    - sixtools
    # - xpdan

about:
  home: https://github.com/NSLS-II
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Bluesky analysis metapackage for NSLS-II beamlines
