{% set name = "nsls2-analysis" %}
{% set year = "2020" %}
{% set cycle = "2" %}
{% set version = "0" %}

package:
  name: {{ name|lower }}
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0
  skip: True  # [py<36]

requirements:
  host:
    - python
  run:
    - python
    # SIX
    - edrixs
    - pycentroids
    - scikit-learn
    - sixtools >=0.0.2
    # ISR
    - eiger-io
    # SRX
    - hxntools
    - pyxrf >=0.0.9
    # ISS
    - isstools
    - mendeleev
    - netcdf4
    - numexpr
    - periodictable
    - pyzbar
    - xraylarch >=0.9.45
    # CHX
    - boto3
    - chxtools
    - graphviz
    - line_profiler
    - memory_profiler
    - modestimage
    - papermill
    # SMI
    - pyfai
    - sasview
    # LIX
    - fabio
    - py4xs
    - lmfit >=0.9.9
    # FXI
    - pypdf2
    - pystackreg
    - reportlab
    - scikit-learn
    - tomopy
    # CSX1
    - csxtools >=0.1.14
    # CSX2
    - csxtools
    - amostra
    # PDF
    - xpdan
    # XPD
    #- xpdan

test:
  imports:
    # SIX
    - edrixs
    - pycentroids
    - scikit-learn
    - sixtools >=0.0.2
    # ISR
    - eiger-io
    # SRX
    - hxntools
    - pyxrf >=0.0.9
    # ISS
    - isstools
    - mendeleev
    - netcdf4
    - numexpr
    - periodictable
    - pyzbar
    - xraylarch >=0.9.45
    # CHX
    - boto3
    - chxtools
    - graphviz
    - line_profiler
    - memory_profiler
    - modestimage
    - papermill
    # SMI
    - pyfai
    - sasview
    # LIX
    - fabio
    - py4xs
    - lmfit >=0.9.9
    # FXI
    - pypdf2
    - pystackreg
    - reportlab
    - scikit-learn
    - tomopy
    # CSX1
    - csxtools >=0.1.14
    # CSX2
    - csxtools
    - amostra
    # PDF
    - xpdan
    # XPD
    #- xpdan

about:
  home: https://github.com/NSLS-II-
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Bluesky analysis metapackage for NSLS-II beamlines
